Match DV disks with volumes
gardener/machine-controller-manager-provider-kubevirt pull request #29
Opened 2020-10-14 16:52 UTC by mfranczy

Signed-off-by: Marcin Franczyk <marcin0franczyk@gmail.com>

**What this PR does / why we need it**:
It allows to pass devices options and matches disks settings with volumes

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator
improvement_user
```

2020-10-14 16:53 UTC, mfranczy commented
@stoyanr PR is still in progress, tomorrow during the sync meeting we have to discuss `volumeSource` type

2020-10-14 16:54 UTC, mfranczy commented on pkg/kubevirt/apis/provider_spec.go
> +// TODO: REMOVE
this must be removed and pulled from the gardener-kubevirt-provider

2020-10-16 08:08 UTC, stoyanr requested changes
Looks very good, I only have a few naming suggestions and a few more regarding wording of comments.

2020-10-16 08:08 UTC, stoyanr commented on pkg/kubevirt/core/util.go
> +	providedDisks []kubevirtv1.Disk,
I would use `configuredDisks` as it's a bit more concrete.
```suggestion
	configuredDisks []kubevirtv1.Disk,
```

2020-10-16 08:08 UTC, stoyanr commented on pkg/kubevirt/validation/validation.go
> +func hasDiskVolumeMatch(diskName string, volumes []api.AdditionalVolumeSpec) bool {
This function checks whether the given slice has a volume with the given name.
```suggestion
func hasVolumeWithName(diskName string, volumes []api.AdditionalVolumeSpec) bool {
```

2020-10-16 08:08 UTC, stoyanr commented on pkg/kubevirt/core/util.go
> +func findDiskByVolumeName(name string, disks []kubevirtv1.Disk) *kubevirtv1.Disk {
Could you please move the 2 helper functions `findDiskByName` and `buildDefaultDisk` below `buildVolumes` for consistency with the rest of the code?

2020-10-16 10:04 UTC, mfranczy commented
@stoyanr I addressed all your comments.

2020-10-16 11:45 UTC, stoyanr approved these changes

2020-10-16 11:45 UTC, merged